name: Test

# Trigger workflow on push or pull requests but only for the "main" branch
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

  # Allow running workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Install Python modules
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vim-vint
      # Run linter
      - name: Lint code using Vint
        run: |
          vint .
      # Run unit tests
      # TODO
